import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

const SUPABASE_URL = process.env.SUPABASE_URL || '';
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || '';
const API_URL = 'http://localhost:3000';

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);
const TARGET_EMAIL = 'admin@recrutos.com';

async function delay(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function runTest() {
  console.log('=== NORMAL MEMORY PROMOTION TEST ===');

  const { data: users } = await supabase.auth.admin.listUsers();
  const user = users?.users.find((u) => u.email === TARGET_EMAIL);
  if (!user) {
    console.log('User not found.');
    return;
  }
  const userId = user.id;

  // 1. Get JWT for chat
  const { data: resetData, error: resetErr } = await supabase.auth.admin.generateLink({
    type: 'recovery',
    email: TARGET_EMAIL,
  });
  
  if (resetErr) {
    console.error('Failed to get reset link:', resetErr);
    return;
  }
  
  const resetUrl = new URL(resetData.properties.action_link);
  const tokenHash = resetUrl.searchParams.get('token');
  
  const { data: authData, error: authErr } = await supabase.auth.verifyOtp({
    token_hash: tokenHash!,
    type: 'recovery',
  });
  
  if (authErr) {
    console.error('Failed to verify OTP:', authErr);
    return;
  }

  const jwt = authData.session?.access_token;

  // 2. Send normal memory message
  const testMessage = "I usually go to the gym on Tuesday evenings.";
  console.log(`> Sending: "${testMessage}"`);

  const startStamp = new Date().toISOString();

  const chatRes = await fetch(`${API_URL}/api/chat`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${jwt}`,
    },
    body: JSON.stringify({ message: testMessage })
  });

  if (!chatRes.ok) {
    console.error('Chat error:', await chatRes.text());
    return;
  }

  const chatData = await chatRes.json();
  console.log(`> Reply: ${chatData.message}`);

  // 3. Wait for pipelines to process
  console.log('Waiting 15 seconds for initial TurnAnalyzer & extraction...');
  await delay(15000);

  // Check working memory for CANDIDATE
  const { data: candidates } = await supabase
    .from('working_memory')
    .select('*')
    .eq('user_id', userId)
    .gte('created_at', startStamp)
    .eq('status', 'CANDIDATE');

  console.log('\n--- Working Memory Candidates Generated ---');
  console.log(JSON.stringify(candidates, null, 2));

  console.log('\nWaiting 45 seconds for candidate worker synthesis to process...');
  await delay(45000);

  // Check candidate_synthesis_claims
  const { data: claims } = await supabase
    .from('candidate_synthesis_claims')
    .select('*')
    .eq('user_id', userId)
    .gte('created_at', startStamp);

  console.log('\n--- Candidate Synthesis Claims ---');
  console.log(JSON.stringify(claims, null, 2));

  // Check durable memories
  const { data: memories } = await supabase
    .from('memories')
    .select('*')
    .eq('user_id', userId)
    .gte('created_at', startStamp);

  console.log('\n--- Durable Memories Generated ---');
  console.log(JSON.stringify(memories, null, 2));

  // Final analysis
  console.log('\n--- FINAL STATUS ---');
  console.log(`CANDIDATES CREATED: ${candidates?.length || 0}`);
  console.log(`CLAIMS CREATED: ${claims?.length || 0}`);
  console.log(`DURABLE MEMORIES: ${memories?.length || 0}`);

  if (candidates && candidates.length > 0 && (!claims || claims.length === 0)) {
    console.log('RESULT: CANDIDATE SYNTHESIS WORKER DID NOT RUN (Worker is stuck)');
  } else if (claims && claims.length > 0 && (!memories || memories.length === 0)) {
    console.log('RESULT: WORKER RAN BUT SYNTHESIS FAILED TO PROMOTE');
  } else if (memories && memories.length > 0) {
    console.log('RESULT: NORMAL MEMORY PROMOTION PASS');
  } else {
    console.log('RESULT: NO CANDIDATES WERE GENERATED BY THE TURN ANALYZER');
  }
}

runTest();
